// Generated by Avaritia-Tweak visual editor. DO NOT EDIT.
// Workspace schema: 1

ServerEvents.recipes(event => {
    const { avaritia } = event.recipes;

    avaritia.shaped_table(
        4,
        "projecte:tome",
        [
            "!!!!!!!!!",
            "!#######!",
            "!#######!",
            "!##!$!##!",
            "!##%&(##!",
            "!##!)!##!",
            "!#######!",
            "!#######!",
            "!!!!!!!!!"
        ],
        {
            "!": "more_avaritia:compressed_infinity",
            "#": "more_avaritia:compressed_infinity_ingot",
            "$": "goety_revelation:halo_of_the_end",
            "%": "avaritia:infinity_chest",
            "&": "minecraft:book",
            "(": "extendedexchange:arcane_tablet",
            ")": "goety_revelation:ascension_halo"
        }
    ).id("avaritia_tweak:new_entry");
});
